services:
  mysql:
    container_name: MySQL
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule
