services:
  - type: web
    name: desafio-nodejs-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:migrate && npm run db:seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: sqlite
